#!/bin/bash

if `which fpm`
then
  fpm -n abcd -t deb -s dir --exclude .git --post-install postinstall -d libapache2-mod-php5 -d php5-gd -d php5-xsl -d php5-yaz -v 1.2 --prefix  /opt -C ../.. ABCD
else
  echo fpm not in installed or not in path.
  exit 1
fi
